# Generated by Django 5.1.1 on 2024-09-25 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_factura_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='igv',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='total',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='detalle',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.factura'),
        ),
    ]
